### ISSUE TITLE
Dash "-" in SSID for wifiSSID cant connect

### ISSUE THREAD

**Issue by marclave** [SuperHouse/esp-open-rtos#156]
Seems like if there is a "-" in the SSID it wont find the network? I am using the MQTT example, can anyone else confirm this?

**Comment by kanflo** [comment]
Hi @marclave. Sorry for the lack of attention, I will try to reproduce this.

**Comment by marclave** [comment]
@kanflo no worries!

**Comment by marclave** [comment]
@kanflo did you have any luck reproducing this?

**Comment by sheinz** [comment]
I tried **http_get** example with SSID containing a dash "-". Everything works fine in my case.
@marclave can you try **http_get** example with your AP?

**Comment by kanflo** [comment]
@marclave I have not had the possibility to try. Went vacation with a dud FTDI-board meaning I can only dry code ESP stuff this week :-/

**Comment by projectgus** [comment]
Silly question, but is it possible the SSID you're having problems with doesn't contain the ASCII dash but instead contains one of the other non-ASCII dash characters?
https://www.cs.tut.fi/~jkorpela/dashes.html

**Comment by AndreaGreco** [comment]
SSID to my house is called `Wi-Fi2` and working fine over ESP8266

**Comment by sheinz** [comment]
I will close this for now, if there's more information regarding this issue, please reopen it.
