### ISSUE TITLE
Building esp-open-rtos as a set of static lilbraries

### ISSUE THREAD

**Issue by resetnow** [SuperHouse/esp-open-rtos#177]
Hello,

Is it possible to build this SDK as a library so it can be used with different build systems and projects? I looked over some makefiles and it seems like there is no way to build just libraries, is this correct?

**Comment by projectgus** [comment]
Hi,

There's a long-standing feature request for this in #28. It needs some changes to the build system, but it should be possible to do (at the moment all "components" are built as individual libraries and then linked. The hard part is probably gathering all the include directories into one place.)

I'm close this issue in favour of #28, but please feel free to add comments on #28 and/or submit a PR if you start work in this direction.

Angus
