### ISSUE TITLE
IRQ driven UART RX

### ISSUE THREAD

**Issue by kanflo** [SuperHouse/esp-open-rtos#22]
I have completed support for this in https://github.com/SuperHouse/esp-open-rtos/commit/e648cd2957c462b7c1715d4210c4f310362ea3f4

The driver is placed in ```extras/serial-driver``` and there is an example program in ```examples/terminal``` showing how to include the driver (it is not included by default).

**TL;DR:**
```_read_r``` in ```newlib_syscalls.c``` is now declared as weak and ```extas/serial-driver/serial_driver.c``` implements a new version of ```_read_r``` that blocks until data is available and reads from a circular buffer filled by the UART0 IRQ handler. The IRQ handler is installed on the first call to ```_read_r```with a small penalty for subsequent calls.

**Comment by projectgus** [comment]
Oops, I forgot you'd opened a dedicated issue for this. Made into a PR in #23.
