### ISSUE TITLE
ESP exception occuring first time on AP mode after power cycle

### ISSUE THREAD

**Issue by chennakeshavaSoC** [SuperHouse/esp-open-rtos#229]
Hi,
We are using esp-open-rtos with ESP-12F in AP mode, we are seeing ESP exception first time on every power cycle, as soon as a device is joined to this AP.

Is there any solution for this?

**Comment by kanflo** [comment]
Normally it should not. Are you using the access_point example program? If not, could you try it?

**Comment by projectgus** [comment]
When you say "on every power cycle", does it come back from the exception reset and work afterwards? Very odd!

Do you have some log output that includes the exception trace? (You can run it through utils/filteroutput.py to resolve symbol names from addresses.)

**Comment by sheinz** [comment]
Hi @chennakeshavaSoC, it's been a while since you reported the problem. Have you solved it? Can we close the issue?
