### ISSUE TITLE
API's for Espressif RTOS SDK 0.9.9

### ISSUE THREAD

**Issue by sarwadenj** [SuperHouse/esp-open-rtos#241]
as esp-open-rtos is based on Espressif RTOS SDK 0.9.9 so where i will get API provided espressif of Espressif RTOS SDK 0.9.9.
Like any pdf.

**Comment by sheinz** [comment]
I haven't found it available on the official Espressif site.
It might not be available at all.
You can check the latest API reference on the Espressif's webpage.
