### ISSUE TITLE
ds18b20 negative temperature calculation error

### ISSUE THREAD

**Issue by y-ponomarev** [SuperHouse/esp-open-rtos#294]
Negative temperature is calculated as a large positive number.

In file `extras/ds18b20/ds18b20.c` fix function `float ds18b20_read_temperature(int pin, ds18b20_addr_t addr)`

Was:
```
float ds18b20_read_temperature(int pin, ds18b20_addr_t addr) {
    uint8_t scratchpad[8];
    int temp;
...
```

Must be:
```
float ds18b20_read_temperature(int pin, ds18b20_addr_t addr) {
    uint8_t scratchpad[8];
    int16_t temp;
...
```

**Comment by sheinz** [comment]
Hi @y-ponomarev,

Thanks for reporting this!

**Comment by sheinz** [comment]
Fixed with https://github.com/SuperHouse/esp-open-rtos/pull/295
