### ISSUE TITLE
printf does not respect sdk_os_install_putc1

### ISSUE THREAD

**Issue by wgprojects** [SuperHouse/esp-open-rtos#300]
A user-supplied implementation of putc does not work in esp-open-rtos like it does for other ESP8266 programs. (e.g. [http://smallbits.marshall-tribe.net/blog/2016/06/15/esp8266-remote-debug](http://smallbits.marshall-tribe.net/blog/2016/06/15/esp8266-remote-debug) and [http://bbs.espressif.com/viewtopic.php?t=218](http://bbs.espressif.com/viewtopic.php?t=218).)
I believe in core/newlib_syscalls.c, in long _write_r(..) both calls to "uart_putc" should instead be calls to "sdk_os_putc", which calls the user-installed putc implementation. 
This way, it is very simple for the end user to switch the serial port that printf messages should appear from.

It appears that overriding/reimplementing _write_r would also work, but it took me hours to even discover where in the code the issue lay, especially since all the documentation around the ESP SDK indicates that it's very simple to install a different uart_putc implementation - so it's my opinion that the change would be a benefit with no downsides.

**Comment by sheinz** [comment]
Hi @wgprojects,

Thanks for reporting this.

I agree that esp-open-rtos might seem confusing when referencing the official Espressif SDK documentation. [Here some differences are explained](https://github.com/SuperHouse/esp-open-rtos/wiki/ESP-SDK-Differences).

I also agree that adding support for user installed `putc` is a benefit with no major downside. So, I'll mark it as a bug and hope we will fix that soon.
