### ISSUE TITLE
bug on sdk_system_rtc_mem_read/sdk_system_rtc_mem_write

### ISSUE THREAD

**Issue by gpreviato** [SuperHouse/esp-open-rtos#328]
Hi guys,
I've found a small bug in the two functions.

in the write the 'write' operation need (obviously) to be:
RTCMEM_SYSTEM[i + des_addr] = src_buf[i];
i.o 
RTCMEM_SYSTEM[i] = src_buf[i];

The same for read:
dest_buf[i] = RTCMEM_SYSTEM[i + src_addr];
i.o.
dest_buf[i] = RTCMEM_SYSTEM[i];

Many thanks for your great job!

Kind regards,

--gra

**Comment by otopetrik** [comment]
Hi @gpreviato,

thanks for the report. It was fixed by #303.
You are probably using an older version.
