### ISSUE TITLE
UDP Multicast is not working in esp8266

### ISSUE THREAD

**Issue by HKRS** [SuperHouse/esp-open-rtos#332]
Hi, 

I'm trying to do UDP multicast communication by using "netconn_join_leave_group" function.

netconn_join_leave_group(struct netconn *conn,
                         ip_addr_t *multiaddr,
                         ip_addr_t *netif_addr,
                         enum netconn_igmp join_or_leave)

Expected result: If there is no group with that multicast, it should create group and join into the group.
Actual result: It's not creating multicast group. So, it can't join in that group and have the multicast communication.
I'm using 
multicast address(2nd argument) is in between 224.0.0.0 and  239.255.255.255 (IP class D)
local ip address as netif_addr (3rd argument)
Please look into this issue.

**Comment by kanflo** [comment]
I have successfully used multicast between an ESP8266 and a Python script. Please have a look at https://github.com/kanflo/opendps/blob/master/esp8266-proxy/uhej.c#L182 and https://github.com/kanflo/opendps/blob/master/dpsctl/dpsctl.py#L368.
