### ISSUE TITLE
vApplicationIdleHook() and vApplicationTickHook()

### ISSUE THREAD

**Issue by SaimenSays** [SuperHouse/esp-open-rtos#349]
Why is undependent function code for `vApplicationIdleHook()` and `vApplicationTickHook()` in app_main.c?
If I want to use own hooks, I get a compiler error, because of double implementation to these of app_main.

**Comment by andrewclink** [comment]
Personally I mark these as weak if I need to override them in my code. I'd be happy to submit a PR if that's an agreeable solution.

**Comment by UncleRus** [comment]
> I'd be happy to submit a PR
That's would be greate!

**Comment by andrewclink** [comment]
I'm writing an example at the same time to demonstrate this and would like to put the chip to sleep in the idle hook. This is just copied from the `simple` example.

Does anyone know the appropriate way of putting the chip to sleep where the FreeRTOS tick event can wake it?

**Comment by andrewclink** [comment]
PR #355. I think this issue can be closed.
