### ISSUE TITLE
.irom0.literal segment not linked properly

### ISSUE THREAD

**Issue by foogod** [SuperHouse/esp-open-rtos#35]
The `IROM` macro causes a data definition to be placed in the .irom0.literal segment, however there's nothing anywhere in the linker scripts to cause .irom0.literal (or any other .irom/.irom0 segment that's not part of the sdklibs) to actually be linked into the final binary.

This results in very bad/confusing things if you actually use the `IROM` macro anywhere in your code..

**Comment by projectgus** [comment]
Sorry again about that one. Merged with comment in #36.
