### ISSUE TITLE
Unresolved include file "hal.h" 

### ISSUE THREAD

**Issue by only1chi** [SuperHouse/esp-open-rtos#361]
interrupts.c in "esp-open-rtos/core/include/esp" needs a file "hal.h".
It references this as "xtensa/hal.h". 
This file doesn't exist in the esp-open-rtos release.

**Comment by resetnow** [comment]
It's a part of esp-open-sdk/lx106-hal https://github.com/tommie/lx106-hal/tree/e4bcc63c9c016e4f8848e7e8f512438ca857531d/include/xtensa
