### ISSUE TITLE
DHCP not working on several chips

### ISSUE THREAD

**Issue by KKoovalsky** [SuperHouse/esp-open-rtos#363]
I used SOFTAP + DHCP + HTTP server on one ESP12E module and everything worked fine. Then I flashed same firmware on other ESP12E modules and what's weird now DHCP doesn't work. When I assign static IP on host (my computer) I can succesfully connect to HTTP server. I used earlier the first ESP12E module with espressif SDK. Could it be problem with blank.bin and esp_init_data_default.bin files?

**Comment by resetnow** [comment]
>Could it be problem with blank.bin and esp_init_data_default.bin files?

Do you flash those files during the firmware download process?

**Comment by KKoovalsky** [comment]
On the working ESP module I did not do that and everything worked fine, but I flashed them earlier and I don't think that they were erased (it's just my guess - I don't know if while flashing whole Flash is erased or only those blocks where FW will be written) and I also do not do that on new modules.
I checked it and flashed also those files, but DHCP is still not working.

**Comment by kanflo** [comment]
No worries, under powering devices is a useful experience ;)

**Comment by KKoovalsky** [comment]
However, sorry one more time, because it is not issue with power supply. :(   
I'm flashing three chips with same file and dhcp won't work on two of them. I checked on the same power supply and DHCP is not working even then. What's not common in this case - I bought the working one earlier and next two ESP12E modules (those not working) in one purchase order. 

On the working chip when I connect to AP I get this log output:
station: MY:MA:CA:DD:RE:SS join, AID = 1
State dump. Message type 3

Nonetheless, when I connect to AP on not working chip I get this log output:
station: MY:MA:CA:DD:RE:SS join, AID = 1
State dump. Message type 1

So there is a difference in "Message type". Implementation I use:
```
	sdk_wifi_set_opmode(STATIONAP_MODE);
	struct ip_info ap_ip;
	IP4_ADDR(&ap_ip.ip, 192, 168, 1, 1);
	IP4_ADDR(&ap_ip.gw, 0, 0, 0, 0);
	IP4_ADDR(&ap_ip.netmask, 255, 255, 255, 0);
	sdk_wifi_set_ip_info(1, &ap_ip);

	struct sdk_softap_config ap_config = {
		.ssid = WIFI_SSID,
		.ssid_hidden = 0,
		.channel = 9,
		.ssid_len = strlen(WIFI_SSID),
		.authmode = AUTH_WPA_WPA2_PSK,
		.password = WIFI_PASS,
		.max_connection = 3,
		.beacon_interval = 100,
	};
	//sdk_wifi_station_disconnect();
	sdk_wifi_softap_set_config(&ap_config);

	ip_addr_t first_client_ip;
	IP4_ADDR(&first_client_ip, 192, 168, 1, 2);
	dhcpserver_start(&first_client_ip, 3);
```
What can I do straighten this situation?

**Comment by ashajjar** [comment]
have you found any solutions to this? I am facing the same problem!

**Comment by ourairquality** [comment]
Use wireshark etc to watch what is happening on the network and look for the start of the problems. When you have some clues then hopefully it is something at a higher layer in lwip or the dhcp client that can be debugged. Try to narrow it down by restricting the mode to station mode.
