### ISSUE TITLE
esp32 compatibility or esp32 port?

### ISSUE THREAD

**Issue by zeroflag** [SuperHouse/esp-open-rtos#383]
Hi, is esp-open-rtos compatible with the esp32? If not, is there any plan to make it compatible? Or maybe this is not possible because of technical reasons and differences between the 2 platforms?

**Comment by kezl** [comment]
Someone else may know better than me, but I think the answer is no, esp32 is already covered by ESP-IDF:

[https://github.com/espressif/esp-idf/releases](url)

Which is the official development framework and I think involves some of the same developers as esp-open-rtos.

**Comment by kanflo** [comment]
That is true. @projectgus who started EOR is now working for Espressif on their IDF.
