### ISSUE TITLE
Did it had some Infrared remote control library？

### ISSUE THREAD

**Issue by IoTServ** [SuperHouse/esp-open-rtos#414]
Thanks！

**Comment by pbendersky** [comment]
Did you ever find something to send IR using esp-open-rtos?

**Comment by pbendersky** [comment]
Looks like it! I’ll try it. Thank you.

**Comment by pbendersky** [comment]
@IoTServ is this IR library working fine for you? I'm seeing the timings are off when sending, so it works only sometimes.
