### ISSUE TITLE
Need a discussion forum for esp-open-rtos

### ISSUE THREAD

**Issue by foogod** [SuperHouse/esp-open-rtos#43]
As discussed a bit on issue #25, GitHub issues are not necessarily the best way to discuss some issues, and a more general-purpose maillist / forum / etc would be very useful.

I believe @projectgus was looking into some options, but am not sure the status on that.  This ticket is just to track the progress on getting something set up (and will hopefully be closed soon :) )

**Comment by projectgus** [comment]
Decided to bite the bullet and just go with a mailing list:
https://groups.google.com/forum/#!forum/esp-open-rtos

Links are added on the main README as well.

**Comment by projectgus** [comment]
(Ping @mikejac & @kanflo who were involvede in the earlier discussion, in case they don't see this otherwise.)

**Comment by seemasinghh** [comment]
I don't have an idea esp-open-RTOS whereas I think to get the training of [RTOS Training in Noida](

https://www.cetpainfotech.com/technology/Rtos-training) so I want to know about RTOS.
