### ISSUE TITLE
i2c clock stretching problem

### ISSUE THREAD

**Issue by gschorcht** [SuperHouse/esp-open-rtos#471]
The implementation limits the maximum duration of clock stretching to only 10 times the duration of function **read_sda**. The I2C specification does not specify any timeout conditions for clock stretching. Each slave can hold SCL down as long as it needs. The master has to wait until SCL goes high before it can continue.

I have a CCS811 sensor here, that produces clock stretchings up to 60 us. With CLOCK_STRETCH=10 the time the master waits before timeout is much too less and the I2C communication fails. Increasing CLOCK_STRETCH to 200 works for this device but might still produce problems with other devices. 

Please increase the CLOCK_STRETCH constant a lot, remove it completly, or make it configurable.

**Comment by kanflo** [comment]
Configurable would be the best option I think.
