### ISSUE TITLE
Update WiFi code, as needed, to address CERT VU-228591

### ISSUE THREAD

**Issue by jeffsf** [SuperHouse/esp-open-rtos#473]
From http://espressif.com/en/media_overview/news/espressif-releases-patches-wifi-vulnerabilities-cert-vu228519

ESP8266 RTOS (ESP8266) master branch, since commit 2fab9e23d779cdd6e5900b8ba2b588e30d9b08c4

**Comment by flannelhead** [comment]
This is already under discussion, please have a look at https://github.com/SuperHouse/esp-open-rtos/issues/468

**Comment by jeffsf** [comment]
Duplicate, or close enough to #468
