### ISSUE TITLE
basename() declared in <libgen.h> but not resolved by linker

### ISSUE THREAD

**Issue by jeffsf** [SuperHouse/esp-open-rtos#482]
With `#include <libgen.h>` references to usages of `basename()` compile, but result in 
```
undefined reference to `basename'
```
during link.

Inability to resolve link also found with `<string.h>`

`esp-open-rtos/libc/xtensa-lx106-elf/include/libgen.h`

**Comment by jeffsf** [comment]
Public-domain code (at least as indicated in the source file) for basename is available at /usr/src/contrib/gcclibs/libiberty/basename.c on a FreeBSD 11.1-RELEASE distribution.

https://svnweb.freebsd.org/base/releng/11.1/contrib/gcclibs/libiberty/basename.c?revision=320486&view=markup

Comment out "unneeded" #include statements and it compiles and appears to run under espo-open-rtos
```
/* #ifdef HAVE_CONFIG_H */
/* #include "config.h" */
/* #endif */
/* #include "ansidecl.h" */
/* #include "libiberty.h" */
/* #include "safe-ctype.h" */
```

**Comment by ourairquality** [comment]
Not sure what is going wrong here, but `basename` appears to be defined in newlib at newlib/libc/string/gnu_basename.c and newlib/libc/unix/basename.c

**Comment by jeffsf** [comment]
I've got a fresh pull of esp-open-rtos as well as a fresh build of esp-open-sdk and not only does `basename` not resolve in the link, but also now having similar problems with `settimeofday`

Will get some minimal examples

**Comment by jeffsf** [comment]
Resolved by https://github.com/SuperHouse/esp-open-rtos/pull/571
