### ISSUE TITLE
Move interrupt vectors to open source

### ISSUE THREAD

**Issue by projectgus** [SuperHouse/esp-open-rtos#5]
Relates to #2 and other libmain replacement functions.

Interrupt vectors are currently in libmain, however some of the user interrupt handling code can be found in the bottom of FreeRTOS/Source/portable/esp8266/port.c

These should probably be combined into a single source file that handles the Xtensa interrupt vectors and the user interrupts.

**Comment by projectgus** [comment]
Have started a file `include/xtensa_interrupts.h` which has inline versions replacing some simple interrupt management functions that were defined in the SDK.

As work on libmain replacement continues then this can probably be fleshed out and made totally independent of libmain.

**Comment by projectgus** [comment]
This is almost entirely done, it just needs some clean up and consolidation as the exception & interrupt handling is currently split between a few different files.

**Comment by foogod** [comment]
Is this done now?  the exception_vectors.S file has been in master for a while now and appears to work fine..

**Comment by projectgus** [comment]
There's still some consolidation for the interrupt side of things. There's a bunch of generic interrupt (rather than exception) management stuff in FreeRTOS/Source/portable/esp8266/port.c and scattered around a couple of other places, it'd be good to have just in a single file in 'core' as they're not really FreeRTOS specific.

**Comment by projectgus** [comment]
I made a bit of progress on this one this morning, will push something for review soon.

**Comment by projectgus** [comment]
Closed as part of #50
