### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by hughandann50th** [SuperHouse/esp-open-rtos#577]
Exactly how are you suppose to install it i know you use the esp install tool all the time but i have never used it. Would you happen to have good documentation on using it? the GitHub info on the esp install tool page wasn't very helpful

Thanks!

**Comment by jeffsf** [comment]
Where in the "Quick Start" section of the [front page of this repo](https://github.com/SuperHouse/esp-open-rtos) are you failing? 

If followed faithfully, those step-by-step directions should lead you to success.

**Comment by hughandann50th** [comment]
thank you just realized that i was typing the terminal command in wrong it copied it and i forgot to get rid of the $``
