### ISSUE TITLE
Unable to compile newer version examples

### ISSUE THREAD

**Issue by karimulla1993** [SuperHouse/esp-open-rtos#581]
I Used esp-open-rtos 4 or 5 months back and the examples compiled with out any errors and even now it complies without any errors. Now I git cloned the newer version and tried compiling the examples and I am getting a lot of errors, Such as 

../../FreeRTOS/Source/include/timers.h:1242:1: error: expected declaration specifiers before 'TickType_t'
 TickType_t xTimerGetPeriod( TimerHandle_t xTimer ) PRIVILEGED_FUNCTION;
../../include/etstimer.h:31:5: error: expected specifier-qualifier-list before 'TimerHandle_t'
     TimerHandle_t timer_handle;

**Comment by Abhesheksh** [comment]
How did you solve this issue? I am facing this right now.
