### ISSUE TITLE
we have an include problem - socket and file implementations conflict

### ISSUE THREAD

**Issue by yesco** [SuperHouse/esp-open-rtos#61]
I was writing a webserver code, it worked fine till I moved my function that called "write()" to another file. Suddenly it wasn't doing anything anymore, just giving errors.

I was attempting to see if I was getting the same write functions so I printed out the pointer:

 printf("response.write=%x\n", (int) write);

turns out, this statement can't compile as write in "this file" is a macro!

Same problem exists with fcntl() function as nonblocking suddenly didn't work on stdio,
because all the levels of macros included the socket functions instead of the file functions.

CC /home/knoppix/GIT/esp-lisp-other/lisp.c
In file included from ../esp-open-rtos/libc/xtensa-lx106-elf/include/sys/fcntl.h:3:0,
                 from ../esp-open-rtos/libc/xtensa-lx106-elf/include/fcntl.h:1,
                 from /home/knoppix/GIT/esp-lisp-other/lisp.c:80:
../esp-open-rtos/libc/xtensa-lx106-elf/include/sys/_default_fcntl.h:44:0: error: "O_NONBLOCK" redefined [-Werror]
 #define O_NONBLOCK _FNONBLOCK
 ^
In file included from ../esp-open-rtos/lwip/lwip/src/include/posix/sys/socket.h:33:0,
                 from /home/knoppix/GIT/esp-lisp-other/lisp.c:74:
../esp-open-rtos/lwip/lwip/src/include/lwip/sockets.h:278:0: note: this is the location of the previous definition
 #define O_NONBLOCK  1 /* nonblocking I/O */

./libc/xtensa-lx106-elf/include/sys/_default_fcntl.h:23:#define _FNONBLOCK      0x4000  /* non blocking I/O (POSIX style) */
./libc/xtensa-lx106-elf/include/sys/_default_fcntl.h:24:#define _FNDELAY        _FNONBLOCK      /* non blocking I/O (4.2 style) */
./libc/xtensa-lx106-elf/include/sys/_default_fcntl.h:44:#define O_NONBLOCK      _FNONBLOCK
./libc/xtensa-lx106-elf/include/sys/_default_fcntl.h:77:#define FNONBIO         _FNONBLOCK      /* XXX fix to be NONBLOCK everywhere */

I'm not sure how to resolve this, but having macros overriding functions gets somewhat complicated..., also having two non-compatible implementations of functions get even worse...
As I can't use "files/io" and "sockets" in the same file.

**Comment by projectgus** [comment]
Hi yesco,

Sorry for the delay in getting back to you. This is indeed an issue, both LWIP and newlib (libc) provide a "POSIX sockets" interface.

The long-term solution is to have newlib's system call implementations detect when a file descriptor belongs to LWIP and redirect those calls to use LWIP, while other operations use the serial port (or a filesystem if/when we support one.) This kind of falls under issue #55.

The short-term solution is to edit lwip/include/lwipopts.h (or make a copy in your local include directory, and edit that) then add this line:

```
#define LWIP_POSIX_SOCKETS_IO_NAMES     0
```

Now, you can use lwip_read(), lwip_write(), lwip_close(), lwip_fcntl() to refer to sockets and the normal names to refer to stdin/stdout.

You can see how this gets interpreted, here:
https://github.com/SuperHouse/esp-lwip/blob/c4765dccec5c01faeb87e5ed65db1c99ff5c9a05/src/include/lwip/sockets.h#L364


Angus
