### ISSUE TITLE
sysparam_set_string ESP8285 

### ISSUE THREAD

**Issue by kiralikbeyin** [SuperHouse/esp-open-rtos#654]
Works well with ESP8266
```
form_param_t *ssid_param = form_params_find(form, "ssid");
    form_param_t *password_param = form_params_find(form, "password");
...
sysparam_set_string("wifi_ssid", ssid_param->value);
    sysparam_set_string("wifi_password", password_param->value);
````
Cant set with ESP8285 - Sonoff 4CH Pro v1.1

Any solution?

**Comment by rafarrocha** [comment]
I had same issue here.
 
It seems "sysparam_create_area" was not able to create this area in flash memory because it wasn't empty...

To solve this:
$ make erase_flash

And flash it again.

**Comment by kiralikbeyin** [comment]
@rafarrocha Thank you so much!
