### ISSUE TITLE
SLC interrupt number

### ISSUE THREAD

**Issue by DagAgren** [SuperHouse/esp-open-rtos#69]
`esp/interrupts.h` seems to be missing some interrupt numbers. In the I2S code supplied by Espressif, interrupt number 1 is used for the SLC, so there should probably be an INUM_SLC = 1 added.

**Comment by projectgus** [comment]
Thanks! I don't know of any other interrupt numbers that are missing, although there might be (just undocumented so far... urgh!)

If you find any more of these please open issues or send PRs for those as well.
