### ISSUE TITLE
Request: BME680 Bosch BSEC library for IAQ values

### ISSUE THREAD

**Issue by HomeKidd** [SuperHouse/esp-open-rtos#734]
Hi guys!

BME680 example seem to be great, but at the moment its just a _fancy BME280_ without **Bosch Sensortec Environmental Cluster** (BSEC). With this the sensor capable of producing bVOC, eCO2 values from gas resistance.

Maybe someone has time to port [BSEC](https://www.bosch-sensortec.com/bst/products/all_products/bsec) for esp-open-rtos 😄

**Comment by UncleRus** [comment]
BSEC license is incompatible
