### ISSUE TITLE
 error: use of an operand of type 'bool' in 'operator++' is forbidden in C++17

### ISSUE THREAD

**Issue by LouisLee985** [SuperHouse/esp-open-rtos#779]
[INFO ]  Installing pass-2 core C gcc compiler
[ERROR]    /home/openrtos/esp-open-sdk/crosstool-NG/.build/src/gcc-4.8.5/gcc/reload1.c:89:24: error: use of an operand of type 'bool' in 'operator++' is forbidden in C++17

**Comment by lee238** [comment]
https://github.com/Freetz-NG/freetz-ng/discussions/396#discussioncomment-1525316

**Comment by LouisLee985** [comment]
https://github.com/Freetz-NG/freetz-ng/discussions/396#discussioncomment-1525316
